### ISSUE TITLE
"Hidden names" does not support patterns

### ISSUE THREAD

**Issue by FKuerten** [folknor/factorio-shuttle#1]
In this line:
https://github.com/folknor/factorio-shuttle/blob/78cfaea615fa4e879480f9d10b2a9b45d457cd18/control.lua#L119
Find is called with true as the third argument, this means that patterns are not supported, i.e, a literal string find is performed. I would like pattern support.
In any case, the documentation says that patterns are supported and gives examples, but those don't work.

**Comment by folknor** [comment]
Thanks for the report!
I remember, before I put it on github, that I added that `true` after I had made this feature and documented it.
But I can't remember the reason right now. Great catch!
I'll take a look tomorrow.

**Comment by folknor** [comment]
So, I can't really find any problems associated with simply changing it back to `station:find(filter)`, and I can't remember why it was problematic - but I do remember that it was.

What I did notice, and what's also noted in the setting tooltip, is that the setting only applies to non-filtered stations - so once you start typing in the filter box at the top, I ignore the setting completely and show buttons for all stations.

I'm not sure if that's sensible, or if the hidden stations should always remain hidden.

Any thoughts on either issue?

**Comment by FKuerten** [comment]
I would say we try `station:find(filter)` and if someone complains we can change it again.

I don't really have an opinion on the other part yet.

**Comment by folknor** [comment]
https://github.com/folknor/factorio-shuttle/releases/tag/v0.1.14

0.1.14 released here with only that change.
I will not put it on the mod portal yet.

**Comment by FKuerten** [comment]
I will try this out.
