### ISSUE TITLE
Desyncs in multiplayer.

### ISSUE THREAD

**Issue by NoxyNixie** [folknor/factorio-shuttle#3]
This mod causes desyncs especially when shuttles arrive at stations without occupants.

I think it desyncs because the variables: `inShuttle` and `investigate` are modified but not properly synchronized (using global) and can therefore differ or cause differences.

You have a peculiar way of writing Lua so I could be wrong about the variables and might be caused by others but I do know it desyncs (The desync reports are way too big to be useful (over 800MB)).

**Comment by folknor** [comment]
Thank you, I loved the sentence `You have a peculiar way of writing Lua` it made me very happy.

I've moved both to storage now and otherwise simplified the mod a lot since 2018 lol :-D
